#!/bin/bash
root -l -b -q dNmiddEta.C
root -l -b -q f3_InteSpect_Kshort.C
root -l -b -q f3_InteSpect_Kstar.C
root -l -b -q f3_InteSpect_Lambda.C
root -l -b -q f3_InteSpect_Omega.C
root -l -b -q f3_InteSpect_Phi.C
root -l -b -q f3_InteSpect_Xi.C
root -l -b -q f4_InteSpect_Kshort_JE.C
root -l -b -q f4_InteSpect_Kstar_JE.C
root -l -b -q f4_InteSpect_Lambda_JE.C
root -l -b -q f4_InteSpect_Omega_JE.C
root -l -b -q f4_InteSpect_Phi_JE.C
root -l -b -q f4_InteSpect_Xi_JE.C
root -l -b -q f5_InteRatio_KPi.C
root -l -b -q f5_InteRatio_KstarPi.C
root -l -b -q f5_InteRatio_LPi.C
root -l -b -q f5_InteRatio_OPi.C
root -l -b -q f5_InteRatio_PhiPi.C
root -l -b -q f5_InteRatio_XPi.C
root -l -b -q f6_InteRatio_KPi_JE.C
root -l -b -q f6_InteRatio_KstarPi_JE.C
root -l -b -q f6_InteRatio_LPi_JE.C
root -l -b -q f6_InteRatio_OPi_JE.C
root -l -b -q f6_InteRatio_PhiPi_JE.C
root -l -b -q f6_InteRatio_XPi_JE.C
root -l -b -q TrkEta.C
