#!/bin/bash
root -l -b -q dNmiddEta.C
#root -l -b -q dNmiddEta_TwoPad.C
root -l -b -q f4_InteSpect_Kshort_JE.C
root -l -b -q f4_InteSpect_Kstar_JE.C
root -l -b -q f4_InteSpect_Lambda_JE.C
root -l -b -q f4_InteSpect_Omega_JE.C
root -l -b -q f4_InteSpect_Phi_JE.C
root -l -b -q f4_InteSpect_Xi_JE.C
root -l -b -q f5_InteRatio_KPi.C
root -l -b -q f5_InteRatio_KstarPi.C
root -l -b -q f5_InteRatio_LPi.C
root -l -b -q f5_InteRatio_OPi.C
root -l -b -q f5_InteRatio_PhiPi.C
root -l -b -q f5_InteRatio_XPi.C
root -l -b -q f6_InteRatio_KPi_JE.C
root -l -b -q f6_InteRatio_KstarPi_JE.C
root -l -b -q f6_InteRatio_LPi_JE.C
root -l -b -q f6_InteRatio_OPi_JE.C
root -l -b -q f6_InteRatio_PhiPi_JE.C
root -l -b -q f6_InteRatio_XPi_JE.C
root -l -b -q InteRatio_JE.C
root -l -b -q InteRatio_UE.C
#root -l -b -q InteSpect_In.C
root -l -b -q InteSpect_JE.C
#root -l -b -q InteSpect_JE_Hist.C
root -l -b -q InteSpect_Kshort.C
root -l -b -q InteSpect_Kstar.C
root -l -b -q InteSpect_Lambda.C
root -l -b -q InteSpect_Omega.C
root -l -b -q InteSpect_Phi.C
root -l -b -q InteSpect_UE.C
root -l -b -q InteSpect_Xi.C
#root -l -b -q MultiStrangewR.C
root -l -b -q RatiowR.C
root -l -b -q TrkEta.C
